import Footer from "./components/footer/footer";
import "./globals.css";


export const metadata = {
  title: "SortaDev | Oussama Douadi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        <Footer />
      </body>
    </html>
  );
}
